### ISSUE TITLE
Support for Geeklog 2.2.0

### ISSUE THREAD

**Issue by jrmain** [Geeklog-Plugins/ogp#3]
I've been holding off upgrading my site to Geeklog 2.2.0, because there's a recommendation to make sure that all plugins are compatible first.

I'm using the latest version of OGP, which is 1.1.9, released around August, 2017.

Does anyone know whether OGP 1.1.9 is compatible with Geeklog 2.2.0? Is there a timeline on modifying OGP for Geeklog 2.2.0 compatibility?

**Comment by eSilverStrike** [comment]
I did a quick check and it looks like it is.  COM_createHTMLDocument appears to be used were it is needed so the OGP plugin should be compatible with Geeklog v2.2.0.  @mystralkk can you confirm?

When I get back in a couple weeks I will actually install it on my test server to 100% confirm if mystralkk doesn't get back to us as I actually plan on using this plugin soon for my social media buttons,

https://github.com/Geeklog-Plugins/ogp/releases

Since you are upgraded it is always recommended to backup your files and database first in case of any other issues.

**Comment by mystralkk** [comment]
I confirmed that the OGP plugin works with Geeklog 2.2.0.

**Comment by eSilverStrike** [comment]
Great. I added it to the list of compatible plugins for Geeklog v2.2.0 on Geeklog.net.

I also added the Tags plugin to the list as well after a quick check of the code.

https://www.geeklog.net/article.php/geeklog-plugins-that-support-v2-2-0
